# Source for `check-versions`: the chart is pulled from this Helm repo, then pushed to OCI.
helmrepo: signalfx/splunk-otel-collector-chart
helmrepoUrl: https://signalfx.github.io/splunk-otel-collector-chart
ocipush: oci://ghcr.io/fernandoquinino-ntx/splunk-otel-collector
